# GitLab CI/CD for Dreamcast Tool (dcload/dc-tool)

image: segadreamcast/toolchains:latest

stages:
  - "Building Scramble"
  - "Building Dreamcast Tool"
  
variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR
  KOS_URL: https://gitlab.com/simulant/community/kallistios-nitro.git  
  KOS_PATH: $CI_BUILDS_DIR/kos
  ENVIRON_SH: $CI_BUILDS_DIR/kos/environ.sh  
  KOS_PACKAGE: $CI_BUILDS_DIR/kos.tar.xz 
   
build:kos-scramble:
  stage: "Building Scramble"
  script:
    - git clone ${KOS_URL} ${KOS_PATH}  
    - cp ${KOS_PATH}/doc/environ.sh.sample ${ENVIRON_SH}
    - sed -i 's/\/opt\/toolchains\/dc\/kos/${KOS_PATH}/' ${ENVIRON_SH}
    - source ${ENVIRON_SH}
    - cd ${KOS_PATH}/utils/scramble && make
    - cd ${KOS_PATH} && tar -cvzhf ${KOS_PACKAGE} utils/scramble/scramble environ.sh
  artifacts:
    paths:    
    - ${KOS_PACKAGE}
    expire_in: 1 week
   
build:dcload-gcc4:
  stage: "Building Dreamcast Tool"
  image: segadreamcast/toolchains:binutils-2.34-gcc-4.7.4-newlib-2.0.0-gdb-9.1
  script:
    - git clone ${KOS_URL} ${KOS_PATH}
    - cd ${KOS_PATH} && tar -xvf ${KOS_PACKAGE}
    - source ${ENVIRON_SH}    
    - cd ${GIT_CLONE_PATH} && make && make install
   
build:dcload-gcc9:
  stage: "Building Dreamcast Tool"
  image: segadreamcast/toolchains:binutils-2.34-gcc-9.3.0-newlib-3.3.0-gdb-9.1
  script:
    - git clone ${KOS_URL} ${KOS_PATH}
    - cd ${KOS_PATH} && tar -xvf ${KOS_PACKAGE}
    - source ${ENVIRON_SH}    
    - cd ${GIT_CLONE_PATH} && make && make install
